### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by DavidVeksler** [Parsely/slackbot#11]
I get the following error:
```
parsely_slackbot
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\parsely_slackbot-script.py", line 11, in <module>
    load_entry_point('parsely-slackbot==1.1.0', 'console_scripts', 'parsely_slackbot')()
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "c:\program files (x86)\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files (x86)\python37-32\lib\site-packages\parsely_slackbot\__init__.py", line 1, in <module>
    from .slackbot import SlackBot
  File "c:\program files (x86)\python37-32\lib\site-packages\parsely_slackbot\slackbot.py", line 8, in <module>
    from parsely import parsely, models
  File "c:\program files (x86)\python37-32\lib\site-packages\parsely\parsely.py", line 1, in <module>
    from models import Post, Author, Section, Topic, Tag, Referrer, Shares
ModuleNotFoundError: No module named 'models'
```

Windows Server 2016, python 3.7 32bit

**Comment by dan-blanchard** [comment]
This is because our underlying Python API was not updated for Python 3 compatibility. Parsely/python-parsely#8 should fix that once it's merged and we cut a new release.

**Comment by dan-blanchard** [comment]
Not quite released yet. Will close when it is.

**Comment by dan-blanchard** [comment]
python-parsely 1.5.0 is out now, so this should no longer be a problem if you upgrade it.
