### ISSUE TITLE
Having trouble starting server with "parsely_slackbot" command

### ISSUE THREAD

**Issue by thomasdintrone** [Parsely/slackbot#8]
Installed the slackbot on my local server and set up the config file as described in the instructions but when I run the "parsely_slackbot" command all I get is a blinking cursor. 

I let it sit for a while to see if it just needed time but it's not the issue.

Any thoughts?

**Comment by hbbtstar** [comment]
hi Thomas!

happy to help- that sounds like it's working correctly and waiting to receive input. Unless your local server is reachable from the internet, you'll be unable to use the slackbot locally; you need to host it in a reachable server so Slack can reach it.

Is your server reachable from the outside? If so, what is the message you get from Slack when you attempt to use the bot?

Let me know if that helps, or if you have any more questions!

**Comment by thomasdintrone** [comment]
Ah ha, ok makes sense. I thought when you typed in the command locally it would grab some extra necessary files and whatnot.

Alright well in that case, ignoring the local server, I actually set up a server using Heroku and downloaded the slackbot zip file here, and put my config file in the root of that folder and then deployed that to Heroku.

I'm assuming I still did something wrong because when I type in the /parsely slash command it's telling me there's a 503_service_error

*All the slack and parsely settings are correct. Is my config file in the wrong place? Or did I miss something else?

**Comment by hbbtstar** [comment]
I haven't tested the slackbot on heroku in a long time- is that error coming from heroku or from slack? The formatting of that error message doesn't seem like it's coming from the slackbot, but rather from heroku or slack itself.

I'm not sure I'll have the time today, but if I can I'll spin up a heroku dyno and see if I can reproduce the error!

**Comment by thomasdintrone** [comment]
That would be great, thanks!

I see that in slack (screenshot attached):
<img width="552" alt="screen shot 2017-06-16 at 12 28 29 pm" src="https://user-images.githubusercontent.com/1208118/27235500-0d3b67f8-528f-11e7-9aa4-cf1f29e1f02c.png">

Not sure if this has anything to do with it, but after I put the files onto heroku and actually went to the app url it shows the "Application Error" screen..

**Comment by thomasdintrone** [comment]
Hi @hbbtstar, just curious if you had a chance to look into this issue or not?

**Comment by hbbtstar** [comment]
sorry, I haven't had a chance yet- this week is quite busy for me. the 503_service_error suggests that the heroku app server is misconfigured somehow: are there any logs on the heroku dyno that might point to the problem you're having?

**Comment by thomasdintrone** [comment]
Understandable, I appreciate you taking the time to help me out. 

So when I look at the Heroku logs I see this error come up when running the "/parsely" command:

2017-06-23T14:19:07.941740+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=POST path="/" host=<<hiding my hostname>> request_id=76874ba2-4d73-4015-b396-22dbc25049ac fwd="<<hiding this as well>>" dyno= connect= service= status=503 bytes= protocol=https

^ Does that tell you something specific?

**Comment by thomasdintrone** [comment]
Ok, I think I got a little further on my own but am still getting an error. 

**Procfile:**
`web: gunicorn parsely_slackbot:app --log-file=-
`

**requirements.txt:**
```
gunicorn
Flask-Slack>=0.1.5
python-parsely>=1.4.3
pyyaml
tzlocal>=1.2
requests
tornado
```

.. and here's now the **error log** I'm seeing:

```
2017-06-23T17:45:37.625966+00:00 heroku[web.1]: Starting process with command `gunicorn parsely_slackbot:app --log-file=-`
2017-06-23T17:45:40.417344+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [4] [INFO] Starting gunicorn 19.7.1
2017-06-23T17:45:40.418056+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [4] [INFO] Listening at: http://0.0.0.0:59365 (4)
2017-06-23T17:45:40.418184+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [4] [INFO] Using worker: sync
2017-06-23T17:45:40.422934+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [8] [INFO] Booting worker with pid: 8
2017-06-23T17:45:40.512612+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [9] [INFO] Booting worker with pid: 9
2017-06-23T17:45:40.615013+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [8] [ERROR] Exception in worker process
2017-06-23T17:45:40.615016+00:00 app[web.1]: Traceback (most recent call last):
2017-06-23T17:45:40.615017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-06-23T17:45:40.615017+00:00 app[web.1]:     worker.init_process()
2017-06-23T17:45:40.615018+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-06-23T17:45:40.615019+00:00 app[web.1]:     self.load_wsgi()
2017-06-23T17:45:40.615019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-06-23T17:45:40.615020+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-06-23T17:45:40.615021+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-06-23T17:45:40.615021+00:00 app[web.1]:     self.callable = self.load()
2017-06-23T17:45:40.615022+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-06-23T17:45:40.615022+00:00 app[web.1]:     return self.load_wsgiapp()
2017-06-23T17:45:40.615023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-06-23T17:45:40.615024+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-06-23T17:45:40.615024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-06-23T17:45:40.615025+00:00 app[web.1]:     __import__(module)
2017-06-23T17:45:40.615026+00:00 app[web.1]:   File "/app/parsely_slackbot/__init__.py", line 1, in <module>
2017-06-23T17:45:40.615026+00:00 app[web.1]:     from .slackbot import SlackBot
2017-06-23T17:45:40.615027+00:00 app[web.1]:   File "/app/parsely_slackbot/slackbot.py", line 8, in <module>
2017-06-23T17:45:40.615027+00:00 app[web.1]:     from parsely import parsely, models
2017-06-23T17:45:40.615028+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/parsely/parsely.py", line 1, in <module>
2017-06-23T17:45:40.615029+00:00 app[web.1]:     from models import Post, Author, Section, Topic, Tag, Referrer, Shares
2017-06-23T17:45:40.615033+00:00 app[web.1]: ModuleNotFoundError: No module named 'models'
2017-06-23T17:45:40.615176+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [8] [INFO] Worker exiting (pid: 8)
2017-06-23T17:45:40.646600+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [9] [ERROR] Exception in worker process
2017-06-23T17:45:40.646604+00:00 app[web.1]: Traceback (most recent call last):
2017-06-23T17:45:40.646605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-06-23T17:45:40.646606+00:00 app[web.1]:     worker.init_process()
2017-06-23T17:45:40.646607+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-06-23T17:45:40.646608+00:00 app[web.1]:     self.load_wsgi()
2017-06-23T17:45:40.646609+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-06-23T17:45:40.646609+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-06-23T17:45:40.646610+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-06-23T17:45:40.646611+00:00 app[web.1]:     self.callable = self.load()
2017-06-23T17:45:40.646611+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-06-23T17:45:40.646612+00:00 app[web.1]:     return self.load_wsgiapp()
2017-06-23T17:45:40.646613+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-06-23T17:45:40.646613+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-06-23T17:45:40.646614+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-06-23T17:45:40.646615+00:00 app[web.1]:     __import__(module)
2017-06-23T17:45:40.646615+00:00 app[web.1]:   File "/app/parsely_slackbot/__init__.py", line 1, in <module>
2017-06-23T17:45:40.646616+00:00 app[web.1]:     from .slackbot import SlackBot
2017-06-23T17:45:40.646617+00:00 app[web.1]:   File "/app/parsely_slackbot/slackbot.py", line 8, in <module>
2017-06-23T17:45:40.646617+00:00 app[web.1]:     from parsely import parsely, models
2017-06-23T17:45:40.646618+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/parsely/parsely.py", line 1, in <module>
2017-06-23T17:45:40.646619+00:00 app[web.1]:     from models import Post, Author, Section, Topic, Tag, Referrer, Shares
2017-06-23T17:45:40.646623+00:00 app[web.1]: ModuleNotFoundError: No module named 'models'
2017-06-23T17:45:40.646785+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-06-23T17:45:40.807396+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [4] [INFO] Shutting down: Master
2017-06-23T17:45:40.807639+00:00 app[web.1]: [2017-06-23 17:45:40 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-06-23T17:45:40.938721+00:00 heroku[web.1]: Process exited with status 3
2017-06-23T17:45:40.951444+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-23T17:46:55.066312+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/" host=<<XX-hidingthis-XX>> request_id=0621405e-39d0-4524-ad40-42034f2fee3f fwd="54.173.160.80" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by thomasdintrone** [comment]
Hi, sorry just wanted to see if you caught my above messages from the other day. I might be able to get through this myself but still need a little guidance from you or someone else over there.

Looks like it might now have to do with that "**ModuleNotFoundError: No module named 'models'**" error which I'm not sure how to alleviate..

 Thanks again.

**Comment by hbbtstar** [comment]
hey @thomasdintrone! sorry about the delay. I had a chance to play with this this morning, and it seems like some of the heroku stuff had changed around since last I futzed with this: I've made a branch that worked for me (heroku branch)- I was able to successfully test it in slack. You should be able to clone that, replace config.yaml with your own information, push to your heroku dyno (I had to specify it with git push heroku heroku:master, otherwise it insists on using the master branch) and you're off to the races!

Let me know if you run into issues with it! 

And no worries: happy to help!

**Comment by thomasdintrone** [comment]
Hey @hbbtstar, unfortunately still hitting that same error so I must be missing something. 

**The exact steps I took:**
1. Cloned the repo
2. Checked out the "heroku" branch
3. Edited the config.yaml file with my info (which I re-verified as all being correct)
4. Pushed to my heroku app using the command you mentioned "git push heroku heroku:master"
5. I saw everything being installed correctly on the server as I pushed it
6. Opened the app in my browser to see if anything changed and still saw the "Application error" window
7. For S's and Giggles, opened a message in Slack and typed in "/parsely posts, 10m" command which returned that 503_service_error message that I mentioned before

8. Not sure if it's even related anymore considering the updates you made to the heroku branch but I typed in "heroku logs" and see that same "**ModuleNotFoundError: No module named 'models'**"

-- 
Does it look like I missed a setting or a step? 

Is there extra actions in my heroku app that I needed to take? Extra add ons I should have added? I literally just created a new app and pushed the files so if there was an extra step I needed to do in Heroku I def didn't do it. 

Let me know as soon as you can. Thanks!

**Comment by hbbtstar** [comment]
ah! I think I know what it is. Can you pop a file in the top-level directory of the repo called:

runtime.txt

and in it have just one line:

```
python-2.7.13
```

the python-parsely wrapper this depends on isn't 3.x compatible yet, and I bet that's what's fouling it up. Commit that file and push it to your heroku and see if it fixes the module error? I must have forgotten to commit that.

EDIT: the docs around that in case you want them (I think my advice above is right, but just in case):

https://devcenter.heroku.com/articles/python-runtimes

**Comment by thomasdintrone** [comment]
Perfect! Works like a charm now! I'd probably recommend adding that file to the heroku branch in case someone else runs into the same issue as me.

Thank you again for your help! Closing..

**Comment by hbbtstar** [comment]
no problem! Glad it's working. and yeah, I'll pop it in there (though ideally we should support 3.x too. One can dream...)
